-- Add status columns to lsp table
ALTER TABLE lsp ADD COLUMN IF NOT EXISTS status TEXT DEFAULT '';
ALTER TABLE lsp ADD COLUMN IF NOT EXISTS no_sk TEXT DEFAULT '';
ALTER TABLE lsp ADD COLUMN IF NOT EXISTS no_lisensi TEXT DEFAULT '';
ALTER TABLE lsp ADD COLUMN IF NOT EXISTS expiry_date TEXT DEFAULT '';
ALTER TABLE lsp ADD COLUMN IF NOT EXISTS last_checked TIMESTAMPTZ DEFAULT NOW();
